GET http://localhost:8080/v1/
Content-Type: application/json; charset=UTF-8

### :id
GET http://localhost:8080/v1/books/3
Content-Type: application/json; charset=UTF-8

### get
GET  http://localhost:8080/v1/books
Content-Type: application/json; charset=UTF-8

### 
POST http://localhost:8080/v1/books
Content-Type: application/json; charset=UTF-8

{
    "title": "The Pragmatic QA",
    "price": "13232",
    "discount": "0",
    "description": "The Pragmatic QA",
    "rating": "5"
}

### ?id
GET http://localhost:8080/v1/query?id=323&price=2000
Content-Type: application/json; charset=UTF-8